# Generated by Django 6.0.1 on 2026-03-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
